### ISSUE TITLE
Notice boxes' CIRCLED INFORMATION SOURCE character may appear as tofu

### ISSUE THREAD

**Issue by alphapapa** [scientific-python/scientific-python-hugo-theme#256]
@jarrodmillman showed me these screenshots of how the notice boxes on the https://scientific-python.org/about/ page look on his Fedora system:

![tofu1](https://github.com/scientific-python/scientific-python-hugo-theme/assets/601365/64bd1030-cde1-4ae2-b880-af90dfdda227)
![tofu2](https://github.com/scientific-python/scientific-python-hugo-theme/assets/601365/c9698aa8-3823-4c9a-8680-14e05f138cff)

We may be able to improve this by ensuring that we select a fallback font that includes this character.

**Comment by stefanv** [comment]
It renders correctly on my Fedora system, so I suppose it's a font issue indeed. Perhaps we should set more stringent font requirements and fallbacks specifically on the class attached to the icon, instead of to the whole website (I'm not sure those fallback routes will make sense to have the same, but could be).
